// angular/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, CommonModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit, OnDestroy {
  title = 'builderbid-angular';
  user: any = null;

  private handleLogin = (event: any) => {
    this.user = event.detail.user;
  };

  private handleLogout = () => {
    this.user = null;
  };

  ngOnInit() {
    window.addEventListener('builderbid:auth:login', this.handleLogin);
    window.addEventListener('builderbid:auth:logout', this.handleLogout);
  }

  ngOnDestroy() {
    window.removeEventListener('builderbid:auth:login', this.handleLogin);
    window.removeEventListener('builderbid:auth:logout', this.handleLogout);
  }
}

<div style="padding: 20px; border: 2px solid #dd0031; border-radius: 8px;">
  <h1 style="color: #dd0031;">Angular Microfrontend</h1>
  <div *ngIf="user" style="margin-bottom: 10px; color: #2ecc71;">
    Currently logged in as: {{ user.name }}
  </div>
  <p>This is the Angular application running within the single-spa shell.</p>
  <nav>
    <a routerLink="/">Local Home</a> | 
    <a routerLink="/test">Local Test Route</a>
  </nav>
  <hr>
  <router-outlet />
</div>

// insurance-tracking/src/App.tsx
import { useState, useEffect } from 'react'
import './App.css'

function App() {
  const [user, setUser] = useState<{ name: string } | null>(null);

  useEffect(() => {
    const handleLogin = (event: any) => {
      setUser(event.detail.user);
    };
    const handleLogout = () => {
      setUser(null);
    };

    window.addEventListener('builderbid:auth:login', handleLogin);
    window.addEventListener('builderbid:auth:logout', handleLogout);

    return () => {
      window.removeEventListener('builderbid:auth:login', handleLogin);
      window.removeEventListener('builderbid:auth:logout', handleLogout);
    };
  }, []);

  return (
    <div style={{ padding: '20px', border: '2px solid #2196F3', borderRadius: '8px' }}>
      <h1 style={{ color: '#2196F3' }}>Insurance Tracking Microfrontend</h1>
      {user && <div style={{ marginBottom: '10px', color: '#2ecc71' }}>Currently logged in as: {user.name}</div>}
      <p>This is the Insurance Tracking application (Port 5175).</p>
      <div className="card">
        <p>Monitor and manage insurance policies.</p>
      </div>
    </div>
  )
}

export default App
